client_config_backend: settings
client_config:
  client_id:   client_secret: 284201674411-030juhsj7js9332m90pdrdbehrsfrr1a.apps.googleusercontent.com
  client_secret: QEFhCMf9wn_8AaDmRlyPgcGu

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install